function SmoothUV2(clip clip, int "radius", int "threshold", int "interlaced")
{
LoadPlugin(AviSynthPluginsDir + "26/SmoothUV2.dll")
        SmoothUV2(clip, radius, threshold, interlaced)
}


function SSHiQ2(clip clip, int "rY", int "rC", int "tY", int "tC", int "str", bool "HQY", bool "HQC", int "interlaced")
{
LoadPlugin(AviSynthPluginsDir + "26/SmoothUV2.dll")
        SSHiQ2(clip, rY, rC, tY, tC, str, HQY, HQC, interlaced)
}