function FixVHSOversharp(clip clip, int brightness_change, int detection_width, int offset) 
{
LoadPlugin(AviSynthPluginsDir + "25/FixVHSOversharp.dll")
        FixVHSOversharp(clip, brightness_change, detection_width, offset) 
}

function FixVHSOversharpL(clip clip, int brightness_change, int detection_width, int offset) 
{
LoadPlugin(AviSynthPluginsDir + "25/FixVHSOversharp.dll")
        FixVHSOversharpL(clip, brightness_change, detection_width, offset) 
}