function Defreq(clip clip, float "fx", float "fy", float "dx", float "dy", float "sharp", float "fx2", float "fy2", float "dx2", float "dy2", float "sharp2", float "fx3", float "fy3", float "dx3", float "dy3", float "sharp3", float "fx4", float "fy4", float "dx4", float "dy4", float "sharp4", float "cutx", float "cuty", int "plane", int "show", bool "info", bool "measure")
{
LoadPlugin(AviSynthPlugins64Dir + "25/Defreq.dll")
        Defreq(clip, fx, fy, dx, dy, sharp, fx2, fy2, dx2, dy2, sharp2, fx3, fy3, dx3, dy3, sharp3, fx4, fy4, dx4, dy4, sharp4, cutx, cuty, plane, show, info, measure)
}